<a href="https://colab.research.google.com/github/ChoSooBeen/DeepLearning_with_PyTorch/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch로 Tensor 선언하기

https://wikidocs.net/52460

In [10]:
import torch

### 1D

In [11]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [12]:
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape

1
torch.Size([7])
torch.Size([7])


### 2D

In [13]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [14]:
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape

2
torch.Size([4, 3])


In [16]:
print(t[:, 1]) # 첫번째 차원을 전체 선택 --> 두번째 차원의 1번 인덱스 인것만 가져온다.
print(t[:, 1].size()) # ↑ 위의 경우의 크기 = 1차원 벡터

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


## Broadcasting

: 행렬 또는 텐서에 대해서 자동으로 크기를 맞춰서 연산을 수행하게 만든다.

In [17]:
# 두 텐서의 크기가 같은 경우

m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [18]:
# Vector + scalar

m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [20]:
# 2 x 1 Vector(m2) + 1 x 2 Vector(m1)

m1 = torch.FloatTensor([[1, 2]]) # [[1,2], [1,2]]
m2 = torch.FloatTensor([[3], [4]]) # [[3,3], [4,4]]
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## 자주 사용되는 기능들

### 행렬의 곱셈 VS 곱셈

**matmul()** VS **mul() =(일반 곱셈)**  

In [21]:
#matmul()
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [22]:
#mul() = *
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### 평균(Mean)

In [23]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [25]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())

tensor(2.5000)


In [27]:
#dim=0 = 첫번째 차원 = 첫번째 행 을 제거하고 평균을 구한다.
#열의 차원은 보존된다. --> 1과 3의 평균을 구하고, 2와 4의 평균을 구한다.
print(t.mean(dim=0))

tensor([2., 3.])


In [28]:
#dim=-1 = 마지막 차원을 제거한다는 의미
print(t.mean(dim=-1))

tensor([1.5000, 3.5000])
