<a href="https://colab.research.google.com/github/ChoSooBeen/DeepLearning_with_PyTorch/blob/main/NumpyToTensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy로 Tensor 만들기

https://wikidocs.net/52460

In [1]:
import numpy as np

### 1D

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [6]:
#.ndim 차원 출력
print('Rank of t: ', t.ndim)

#.shape 크기 출력
print('Shape of t: ', t.shape) # (7, ) = (1, 7) = (1 x 7)

Rank of t:  1
Shape of t:  (7,)


### 2D

In [7]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [9]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape) # 4행 3열

Rank  of t:  2
Shape of t:  (4, 3)
